### ISSUE TITLE
Keyboard Events do not work in IE?

### ISSUE THREAD

**Issue by CodeLuca** [StrykerKKD/dartrocket#3]
Hey,
I have people at school trying to test out a game that I made and I don't think Keyboard events work. It works fine in Chrome though. The machines are running Windows 8 and a new version of IE. Help?
The game:
http://codeluca.uk/game/rocketgame.html
Thanks

**Comment by StrykerKKD** [comment]
I only use Linux and so I can only test cross platform browsers. Not to mention I only plan to support Firefox and Chrome.
